// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtCgAxzltn5AqXCHWD1qBPxeYwPujCIM',
    appId: '1:577859373866:web:3a99f659cc35c8ef89ac53',
    messagingSenderId: '577859373866',
    projectId: 'propgenieapp',
    authDomain: 'propgenieapp.firebaseapp.com',
    storageBucket: 'propgenieapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1g2ReseLNVlNlwBbjp0mpFaLqWG1DwN8',
    appId: '1:577859373866:android:442f7c06c1a3f2f589ac53',
    messagingSenderId: '577859373866',
    projectId: 'propgenieapp',
    storageBucket: 'propgenieapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSn0MFlxFak7ps16lxviU6Rdhq-Pdh3Sk',
    appId: '1:577859373866:ios:7cfefe30e55adcee89ac53',
    messagingSenderId: '577859373866',
    projectId: 'propgenieapp',
    storageBucket: 'propgenieapp.firebasestorage.app',
    iosClientId: '577859373866-aujfcpvg42dtq9lq2c829laaicoinrpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.propgenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSn0MFlxFak7ps16lxviU6Rdhq-Pdh3Sk',
    appId: '1:577859373866:ios:7cfefe30e55adcee89ac53',
    messagingSenderId: '577859373866',
    projectId: 'propgenieapp',
    storageBucket: 'propgenieapp.firebasestorage.app',
    iosClientId: '577859373866-aujfcpvg42dtq9lq2c829laaicoinrpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.propgenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNtCgAxzltn5AqXCHWD1qBPxeYwPujCIM',
    appId: '1:577859373866:web:887e60f941783ba789ac53',
    messagingSenderId: '577859373866',
    projectId: 'propgenieapp',
    authDomain: 'propgenieapp.firebaseapp.com',
    storageBucket: 'propgenieapp.firebasestorage.app',
  );
}
